# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  workflow_run:
    workflows: ['Run Linter']
    branches: [master]
    types:
      - completed

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Build source
        run: yarn build

      - name: Run tests
        run: yarn test
